
[0m[7m[1m[33m NX [39m[22m[27m[0m  [33mNx Daemon is not enabled. Assets will not be updated when they are changed.[39m

node:internal/process/promises:389
      new UnhandledPromiseRejection(reason);
      ^

UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
[90m    at throwUnhandledRejectionsMode (node:internal/process/promises:389:7)[39m
[90m    at processPromiseRejections (node:internal/process/promises:470:17)[39m
[90m    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)[39m {
  code: [32m'ERR_UNHANDLED_REJECTION'[39m
}

Node.js v20.16.0
